<?php

/**
 * @file
 * Module file for Registration role.
 */

use \Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function registration_role_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.registration_role':
      $output = t("Auto-assign a role upon registration.");
      return $output;
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for user entities.
 */
function registration_role_user_presave(UserInterface $user) {
  if ($user->isNew()) {
    $config = \Drupal::config('registration_role.setting');

    foreach ($config->get('role_to_select') as $key => $value) {
      if ($value) {
        $user->addRole($key);
      }
    }
  }
}
